apiVersion: autoscaling/v2           # API version for HPA

kind: HorizontalPodAutoscaler        # Create an HPA

metadata:                            # Information about HPA
  name: my-app-hpa                   # HPA name

spec:                                # Desired autoscaling configuration

  scaleTargetRef:                    # Which resource should be scaled?
    apiVersion: apps/v1              # API version of target
    kind: Deployment                 # Target is a Deployment
    name: my-app                     # Deployment name

  minReplicas: 2                     # Minimum number of Pods
  maxReplicas: 10                    # Maximum number of Pods

  metrics:                           # Metrics used for scaling

    - type: Resource                 # Use resource metrics

      resource:                      # Resource to monitor
        name: cpu                    # Monitor CPU

        target:                      # Target CPU usage
          type: Utilization           # CPU percentage
          averageUtilization: 70      # Target average CPU is 70%